# Generated by Django 2.2 on 2021-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('qusetion_name', models.CharField(max_length=250)),
                ('question_type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(related_name='question', to='forms.Choices')),
            ],
        ),
    ]
