# Generated by Django 2.2 on 2021-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.SmallIntegerField(choices=[(0, 'yesorno'), (1, 'choiceType'), (2, 'rating'), (3, 'inputType')], default=3),
        ),
    ]
