# Generated by Django 2.2 on 2021-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210210_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='question', to='forms.Choices'),
        ),
    ]
