# Generated by Django 2.2 on 2021-02-17 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_answers_choices_questions_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
