# Generated by Django 2.2 on 2021-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_questions_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Answers', models.ManyToManyField(default=None, null=True, to='forms.Answers')),
                ('Questions', models.ManyToManyField(default=None, to='forms.Questions')),
            ],
        ),
    ]
