# Generated by Django 2.2 on 2021-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='Answers',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='forms.Answers'),
        ),
    ]
