# Generated by Django 2.2 on 2021-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210220_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='Answers',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='Questions',
            new_name='questions',
        ),
    ]
