# Generated by Django 2.2 on 2021-02-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210220_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
    ]
