# Generated by Django 2.2 on 2021-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_remove_questions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='template',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
