# Generated by Django 2.2 on 2021-02-22 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0017_auto_20210220_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forms',
            name='template',
            field=models.SmallIntegerField(choices=[(0, 'template1'), (1, 'template2')], default=0),
        ),
    ]
