# Generated by Django 2.2 on 2021-02-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20210222_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='user',
        ),
        migrations.AlterField(
            model_name='forms',
            name='template',
            field=models.SmallIntegerField(choices=[(1, 'template1'), (2, 'template2')], default=1),
        ),
    ]
